In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\HP\Downloads\netflix_movies_detailed_up_to_2025 (2).csv')

In [3]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,genres,language,popularity,vote_count,vote_average,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,United States of America,16-05-2010,02-07-1905,6.38,"Comedy, Adventure, Fantasy, Animation, Family",en,204,7449,6.38,752600867
1,27205,Movie,Inception,Christopher Nolan,"United Kingdom, United States of America",15-07-2010,02-07-1905,8.37,"Action, Science Fiction, Adventure",en,156,37119,8.37,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"United Kingdom, United States of America",17-11-2010,02-07-1905,7.74,"Adventure, Fantasy",en,121,19327,7.74,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno",United States of America,24-11-2010,02-07-1905,7.60,"Animation, Family, Adventure",en,112,11638,7.60,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois",United States of America,18-03-2010,02-07-1905,7.80,"Fantasy, Adventure, Animation, Family",en,110,13259,7.80,494879471

In [4]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'genres', 'language', 'popularity',
       'vote_count', 'vote_average', 'revenue'],
      dtype='str')

In [5]:
df.shape

(16000, 14)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  str
 2   title         16000 non-null  str
 3   director      15868 non-null  str
 4   country       15534 non-null  str
 5   date_added    16000 non-null  str
 6   release_year  16000 non-null  str
 7   rating        16000 non-null  float64
 8   genres        15893 non-null  str
 9   language      16000 non-null  str
 10  popularity    16000 non-null  int64
 11  vote_count    16000 non-null  int64
 12  vote_average  16000 non-null  float64
 13  revenue       16000 non-null  int64
dtypes: float64(2), int64(4), str(8)
memory usage: 1.7 MB

In [7]:
df.columns=df.columns.str.upper()
df.columns=df.columns.str.replace(' ','_')

In [8]:
df.head()

,SHOW_ID,TYPE,TITLE,DIRECTOR,COUNTRY,DATE_ADDED,RELEASE_YEAR,RATING,GENRES,LANGUAGE,POPULARITY,VOTE_COUNT,VOTE_AVERAGE,REVENUE
0,10192,Movie,Shrek Forever After,Mike Mitchell,United States of America,16-05-2010,02-07-1905,6.38,"Comedy, Adventure, Fantasy, Animation, Family",en,204,7449,6.38,752600867
1,27205,Movie,Inception,Christopher Nolan,"United Kingdom, United States of America",15-07-2010,02-07-1905,8.37,"Action, Science Fiction, Adventure",en,156,37119,8.37,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"United Kingdom, United States of America",17-11-2010,02-07-1905,7.74,"Adventure, Fantasy",en,121,19327,7.74,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno",United States of America,24-11-2010,02-07-1905,7.60,"Animation, Family, Adventure",en,112,11638,7.60,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois",United States of America,18-03-2010,02-07-1905,7.80,"Fantasy, Adventure, Animation, Family",en,110,13259,7.80,494879471

In [9]:
df.columns

Index(['SHOW_ID', 'TYPE', 'TITLE', 'DIRECTOR', 'COUNTRY', 'DATE_ADDED',
       'RELEASE_YEAR', 'RATING', 'GENRES', 'LANGUAGE', 'POPULARITY',
       'VOTE_COUNT', 'VOTE_AVERAGE', 'REVENUE'],
      dtype='str')

In [10]:
df.isnull().sum()

SHOW_ID           0
TYPE              0
TITLE             0
DIRECTOR        132
COUNTRY         466
DATE_ADDED        0
RELEASE_YEAR      0
RATING            0
GENRES          107
LANGUAGE          0
POPULARITY        0
VOTE_COUNT        0
VOTE_AVERAGE      0
REVENUE           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dropna(inplace=True)

In [13]:
df.isnull().sum()

SHOW_ID         0
TYPE            0
TITLE           0
DIRECTOR        0
COUNTRY         0
DATE_ADDED      0
RELEASE_YEAR    0
RATING          0
GENRES          0
LANGUAGE        0
POPULARITY      0
VOTE_COUNT      0
VOTE_AVERAGE    0
REVENUE         0
dtype: int64

In [14]:
df.shape

(15422, 14)

In [15]:
df.duplicated().nunique()

1

In [16]:
df.isnull().nunique()

SHOW_ID         1
TYPE            1
TITLE           1
DIRECTOR        1
COUNTRY         1
DATE_ADDED      1
RELEASE_YEAR    1
RATING          1
GENRES          1
LANGUAGE        1
POPULARITY      1
VOTE_COUNT      1
VOTE_AVERAGE    1
REVENUE         1
dtype: int64

In [17]:
duplicates=df[df.duplicated()]
print(f"Total duplicate rows:{len(duplicates)}")

Total duplicate rows:0

In [18]:
df.loc[2]

SHOW_ID                                                12444
TYPE                                                   Movie
TITLE           Harry Potter and the Deathly Hallows: Part 1
DIRECTOR                                         David Yates
COUNTRY             United Kingdom, United States of America
DATE_ADDED                                        17-11-2010
RELEASE_YEAR                                      02-07-1905
RATING                                                  7.74
GENRES                                    Adventure, Fantasy
LANGUAGE                                                  en
POPULARITY                                               121
VOTE_COUNT                                             19327
VOTE_AVERAGE                                            7.74
REVENUE                                            954305868
Name: 2, dtype: object

In [19]:
df.count()

SHOW_ID         15422
TYPE            15422
TITLE           15422
DIRECTOR        15422
COUNTRY         15422
DATE_ADDED      15422
RELEASE_YEAR    15422
RATING          15422
GENRES          15422
LANGUAGE        15422
POPULARITY      15422
VOTE_COUNT      15422
VOTE_AVERAGE    15422
REVENUE         15422
dtype: int64

In [20]:
df['TITLE']

0                                 Shrek Forever After
1                                           Inception
2        Harry Potter and the Deathly Hallows: Part 1
3                                             Tangled
4                            How to Train Your Dragon
                             ...
15989                                        Psykopat
15990                              Blood and Stuffing
15991                               To a Land Unknown
15996                                   Man and Woman
15999                                  Portal to Hell
Name: TITLE, Length: 15422, dtype: str

In [21]:
df['DIRECTOR']

0                        Mike Mitchell
1                    Christopher Nolan
2                          David Yates
3           Byron Howard, Nathan Greno
4          Chris Sanders, Dean DeBlois
                     ...
15989    Matthew Hart, Renaldo Samsara
15990                        Ray Brown
15991                    Mahdi Fleifel
15996                    Vladimir Kott
15999                       Woody Bess
Name: DIRECTOR, Length: 15422, dtype: str

In [22]:
df[['TITLE','DIRECTOR']].head(10)

                                          TITLE                     DIRECTOR
0                           Shrek Forever After                Mike Mitchell
1                                     Inception            Christopher Nolan
2  Harry Potter and the Deathly Hallows: Part 1                  David Yates
3                                       Tangled   Byron Howard, Nathan Greno
4                      How to Train Your Dragon  Chris Sanders, Dean DeBlois
5                                Shutter Island              Martin Scorsese
6                                The Karate Kid                 Harald Zwart
7                                    Iron Man 2                  Jon Favreau
8                                     Grown Ups                 Dennis Dugan
9                                  Room in Rome                  Julio Medem

In [23]:
df[['COUNTRY','RATING']].head(10)

                                      COUNTRY  RATING
0                    United States of America    6.38
1    United Kingdom, United States of America    8.37
2    United Kingdom, United States of America    7.74
3                    United States of America    7.60
4                    United States of America    7.80
5                    United States of America    8.20
6  China, Hong Kong, United States of America    6.50
7                    United States of America    6.80
8                    United States of America    6.39
9                               France, Spain    6.42

In [24]:
(df['VOTE_COUNT']==df['VOTE_AVERAGE']).all()

np.False_

In [25]:
df.head()

,SHOW_ID,TYPE,TITLE,DIRECTOR,COUNTRY,DATE_ADDED,RELEASE_YEAR,RATING,GENRES,LANGUAGE,POPULARITY,VOTE_COUNT,VOTE_AVERAGE,REVENUE
0,10192,Movie,Shrek Forever After,Mike Mitchell,United States of America,16-05-2010,02-07-1905,6.38,"Comedy, Adventure, Fantasy, Animation, Family",en,204,7449,6.38,752600867
1,27205,Movie,Inception,Christopher Nolan,"United Kingdom, United States of America",15-07-2010,02-07-1905,8.37,"Action, Science Fiction, Adventure",en,156,37119,8.37,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"United Kingdom, United States of America",17-11-2010,02-07-1905,7.74,"Adventure, Fantasy",en,121,19327,7.74,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno",United States of America,24-11-2010,02-07-1905,7.60,"Animation, Family, Adventure",en,112,11638,7.60,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois",United States of America,18-03-2010,02-07-1905,7.80,"Fantasy, Adventure, Animation, Family",en,110,13259,7.80,494879471

In [26]:
df[['GENRES','LANGUAGE']].head(10)

                                          GENRES LANGUAGE
0  Comedy, Adventure, Fantasy, Animation, Family       en
1             Action, Science Fiction, Adventure       en
2                             Adventure, Fantasy       en
3                   Animation, Family, Adventure       en
4          Fantasy, Adventure, Animation, Family       en
5                       Drama, Thriller, Mystery       en
6               Action, Adventure, Drama, Family       en
7             Adventure, Action, Science Fiction       en
8                                         Comedy       en
9                                 Drama, Romance       es

In [29]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\hp\jupyter_env\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\hp\jupyter_env\lib\site-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in c:\users\hp\jupyter_env\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\jupyter_env\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
from sqlalchemy import create_engine

username="postgres"
password="ShivaRubi0226"
host="localhost"
port="5432"
database="netflix_analysis"

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="netflix"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data successfully loaded into table'{table_name}' in database '{database}'.")

Data successfully loaded into table'netflix' in database 'netflix_analysis'.